# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Zybo-Z7-Master.xdc

# Block Designs: bd/numero7_block/numero7_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==numero7_block || ORIG_REF_NAME==numero7_block} -quiet] -quiet

# IP: bd/numero7_block/ip/numero7_block_dvi2rgb_0_0/numero7_block_dvi2rgb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==numero7_block_dvi2rgb_0_0 || ORIG_REF_NAME==numero7_block_dvi2rgb_0_0} -quiet] -quiet

# IP: bd/numero7_block/ip/numero7_block_rgb2dvi_0_0/numero7_block_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==numero7_block_rgb2dvi_0_0 || ORIG_REF_NAME==numero7_block_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/numero7_block/ip/numero7_block_clk_wiz_0_0/numero7_block_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==numero7_block_clk_wiz_0_0 || ORIG_REF_NAME==numero7_block_clk_wiz_0_0} -quiet] -quiet

# IP: bd/numero7_block/ip/numero7_block_xlconstant_0_0/numero7_block_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==numero7_block_xlconstant_0_0 || ORIG_REF_NAME==numero7_block_xlconstant_0_0} -quiet] -quiet

# IP: bd/numero7_block/ip/numero7_block_rgb_switch_0_1/numero7_block_rgb_switch_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==numero7_block_rgb_switch_0_1 || ORIG_REF_NAME==numero7_block_rgb_switch_0_1} -quiet] -quiet

# XDC: /home/vini/Documents/FPGA/GIF4202_Lab3/numero7_a/numero7_a.gen/sources_1/bd/numero7_block/numero7_block_ooc.xdc
