set_property IOSTANDARD LVCMOS18 [get_ports {data[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports tx]
set_property IOSTANDARD LVCMOS18 [get_ports termine]
set_property IOSTANDARD LVCMOS18 [get_ports reset]
set_property IOSTANDARD LVCMOS18 [get_ports start]
set_property IOSTANDARD LVCMOS18 [get_ports occupe]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property PACKAGE_PIN V18 [get_ports {data[5]}]
set_property PACKAGE_PIN V17 [get_ports {data[4]}]
set_property PACKAGE_PIN U15 [get_ports {data[3]}]
set_property PACKAGE_PIN U14 [get_ports {data[2]}]
set_property PACKAGE_PIN R14 [get_ports {data[1]}]
set_property PACKAGE_PIN P14 [get_ports {data[0]}]
set_property PACKAGE_PIN W15 [get_ports tx]
set_property PACKAGE_PIN W16 [get_ports termine]
set_property PACKAGE_PIN T15 [get_ports reset]
set_property PACKAGE_PIN T14 [get_ports start]
set_property PACKAGE_PIN V12 [get_ports occupe]
set_property PACKAGE_PIN K17 [get_ports clk]

create_clock -period 8.000 -name clk -waveform {0.000 4.000} [get_ports clk]
