# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/numero8_constraints.xdc

# Block Designs: bd/numero8_block/numero8_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==numero8_block || ORIG_REF_NAME==numero8_block} -quiet] -quiet

# IP: bd/numero8_block/ip/numero8_block_dvi2rgb_0_0/numero8_block_dvi2rgb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==numero8_block_dvi2rgb_0_0 || ORIG_REF_NAME==numero8_block_dvi2rgb_0_0} -quiet] -quiet

# IP: bd/numero8_block/ip/numero8_block_rgb2dvi_0_0/numero8_block_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==numero8_block_rgb2dvi_0_0 || ORIG_REF_NAME==numero8_block_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/numero8_block/ip/numero8_block_clk_wiz_0_0/numero8_block_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==numero8_block_clk_wiz_0_0 || ORIG_REF_NAME==numero8_block_clk_wiz_0_0} -quiet] -quiet

# IP: bd/numero8_block/ip/numero8_block_color_detector_0_0/numero8_block_color_detector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==numero8_block_color_detector_0_0 || ORIG_REF_NAME==numero8_block_color_detector_0_0} -quiet] -quiet

# XDC: /home/vini/Documents/FPGA/GIF4202_Lab3/numero8/numero8.gen/sources_1/bd/numero8_block/numero8_block_ooc.xdc
