# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vini/Documents/FPGA/GIF4202_Lab3/numero9/numero9.srcs/sources_1/bd/numero8_block/ip/numero8_block_proc_sys_reset_0_0/numero8_block_proc_sys_reset_0_0.xci
# IP: The module: 'numero8_block_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vini/Documents/FPGA/GIF4202_Lab3/numero9/numero9.gen/sources_1/bd/numero8_block/ip/numero8_block_proc_sys_reset_0_0/numero8_block_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'numero8_block_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/vini/Documents/FPGA/GIF4202_Lab3/numero9/numero9.gen/sources_1/bd/numero8_block/ip/numero8_block_proc_sys_reset_0_0/numero8_block_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'numero8_block_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/vini/Documents/FPGA/GIF4202_Lab3/numero9/numero9.gen/sources_1/bd/numero8_block/ip/numero8_block_proc_sys_reset_0_0/numero8_block_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'numero8_block_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/vini/Documents/FPGA/GIF4202_Lab3/numero9/numero9.srcs/sources_1/bd/numero8_block/ip/numero8_block_proc_sys_reset_0_0/numero8_block_proc_sys_reset_0_0.xci
# IP: The module: 'numero8_block_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vini/Documents/FPGA/GIF4202_Lab3/numero9/numero9.gen/sources_1/bd/numero8_block/ip/numero8_block_proc_sys_reset_0_0/numero8_block_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'numero8_block_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/vini/Documents/FPGA/GIF4202_Lab3/numero9/numero9.gen/sources_1/bd/numero8_block/ip/numero8_block_proc_sys_reset_0_0/numero8_block_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'numero8_block_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/vini/Documents/FPGA/GIF4202_Lab3/numero9/numero9.gen/sources_1/bd/numero8_block/ip/numero8_block_proc_sys_reset_0_0/numero8_block_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'numero8_block_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
